### ISSUE TITLE
각자 유저 시나리오까지 검증해오기

### ISSUE THREAD

**Issue by Err0rCode7** [42CodeTogether/docs#16]
- [x] 자이님
- [x] 새우전님
- [x] 재욱킴님
- [x] 승옐님
- [x] 재스킴님

**Comment by idjaeha** [comment]
유저 스토리와 유저 시나리오를 비교하여 빠진 내용이 없다는 것을 확인했습니다.
다만 유저 시나리오의 마지막 부분인 매칭된 *팀의 정보 확인 기능 부분이 유저 스토리와 내용은 일치하지만 사용 단어가 조금 다르다는 점이 있습니다.

**Comment by Err0rCode7** [comment]
## 부족한 점
- 유저 시나리오에서 어드민 바로 위에 시나리오의 상황과 기능의 맥락과 니즈와 사용자 행동의 맥락이 어울리지 않습니다.
- 유저 시나리오에서 팀 완료 취소 신청 기능 관련된 내용이 없습니다.
- 유저 시나리오 제일 하단의 내용에 문제가 보입니다.
  - 사용자 행동을 `매칭된 *팀의 정보를 *활동 내역에서 확인한다.` 로 수정하는게 좋을 것 같습니다. 그리고 엮여있는 유저 스토리의 행동을 `*활동 내역에서 *현재 팀 내역을 확인한다.` 로 수정해야할 것 같습니다.
  - 기능을 `*활동 내역 확인 기능`이나 `*현재 팀 내역 확인 기능`으로 하는 것이 좋을 것 같습니다.
- 정의한 Dict의 *현재 팀 내역의 내용을 `현재 참여하고있는 팀 내역 및 *자신의 팀의 정보`로 수정이 필요합니다.
- `*누적 팀 기록`, `*예약 내역`, `* 현재 팀 내역`을 확인하는 유저 시나리오의 기능이 `*활동 내역 확인 기능`으로만 되어있는데 추가로 각각의 확인 기능도 적는 것이 좋을 것 같습니다. 

## 추가 의견
- 활동 내역에서 예약 내역이 현재 자신이 예약을 한 것을 나타내는 걸로 알고있는데 활동 내역에서 예약을 취소할 수 있는 시나리오를 추가하는 것이 어떨까요?

**Comment by 2winyear** [comment]
유저 스토리와 유저 시나리오 부분 내용 확인하였습니다.
