### ISSUE TITLE
시퀀스 분담 - 재서

### ISSUE THREAD

**Issue by Err0rCode7** [42CodeTogether/docs#17]
- [x] 서브젝트 추가
- [x] 서브젝트 삭제
- [x] 서브젝트 설정
- [x] 42 서브젝트 목록 확인

**Comment by JaeSeoKim** [comment]
![admin](https://raw.githubusercontent.com/42CodeTogether/docs/e5a895071714d47a595b567786a4261c60d1058b/admin.svg)

**Comment by JaeSeoKim** [comment]
@Err0rCode7 서브젝트 추가 완성 했습니다. 한번 이런 형태로 만드는 것이 정상적인지 확인 부탁드려요!

조금 걸리는 점은 완성하고 보니깐 controller의 로직을 ref로 뻇어야 할 것 같네요 ㅠ

**Comment by JaeSeoKim** [comment]
![mvp 확장-서브젝트 추가](https://user-images.githubusercontent.com/48559454/118399769-a76b2300-b699-11eb-9b14-ca5b0e03e15b.png)

**Comment by Err0rCode7** [comment]
> @Err0rCode7 서브젝트 추가 완성 했습니다. 한번 이런 형태로 만드는 것이 정상적인지 확인 부탁드려요!
> 
> 조금 걸리는 점은 완성하고 보니깐 controller의 로직을 ref로 뻇어야 할 것 같네요 ㅠ

넵 ! 컨트롤러에서 하나의 레퍼런스로 빼서 처리하는 것으로 표현하면 저희가 통일 시킨 방법으로 잘 작성하신것 같아요 ~

아 그리고 한 객체에서 다른 객체로 요청을 보내려고 ref으로 빼실 때 요청 화살표가 바로 ref 박스를 가리키게해서 생명 주기 박스를 안그려도 될 수 있게 통일 시키는 게 어떨까요? 어차피 생명 주기는 ref에서 끝나니까요 !
https://app.diagrams.net/#G1QSxSFhX4_6to0JY1FS8SCAfeTMdQXgxZ 에서 `|승원 시작` 바로 오른쪽 텝에서 제가 한 예시를 보면 이해되실꺼에요

추가로 요청할 때 화살표 머리 모양과 반환하는 화살표 머리 모양이 잘못된 것 같네요 ~
[5월 14일 금요일](https://42codetogether.atlassian.net/wiki/spaces/42CODETOGE/pages/74842113/2021-05-14) 회의록에서 확인하실 수 있어요 !
