### ISSUE TITLE
시퀀스 분담 - 재하

### ISSUE THREAD

**Issue by Err0rCode7** [42CodeTogether/docs#20]
- [x] 로그인
- [x] 예약 내역 확인
- [x] 현재 팀 내역 확인
- [x] 누적 팀 내역 확인

**Comment by idjaeha** [comment]
- [ ] 팀 관리
- [ ] 팀 해체 설정
- [ ] 팀 해체 신청
- [ ] 팀 해체 취소
- [ ] 팀 해체 피드백

**Comment by idjaeha** [comment]
궁금증
- db에 저장 메시지 보내고 반환도 나올까요?

할 말
- 제 부분이 적긴하네요... ㅎㅎ
- 팀 관리, 팀 해체 설정이 사실상 없는 부분이라............. 감사합니다 재욱형 @napaholic

**Comment by idjaeha** [comment]
- [ ] 디폴트 매칭 주기 설정 피드백 사항 수정하기

**Comment by idjaeha** [comment]
아래의 3개 로직을 완료했습니다.
- 예약 내역 확인
- 현재 팀 내역 확인
- 누적 팀 내역 확인

3개의 로직 모두 컨트롤러에서 ref로 상세 로직을 빼내려고 했으나, 사실상 조회하는 로직 밖에 존재하지 않아서 따로 빼내지 않고 작성했습니다.

**Comment by idjaeha** [comment]
로그인 완료했습니다!
